### ISSUE TITLE
Error in writing HDF5 outputs

### ISSUE THREAD

**Issue by ymbahe** [ICRAR/VELOCIraptor-STF#113]
On cosma7 with a recent fresh clone, I encounter the following error: 

```
stf: /cosma7/data/dp004/dc-bahe1/BH_REPOS/VELOCIraptor-STF/src/h5_output_file.cxx:322: void H5OutputFile::write_attribute(const string&, const string&, hid_t, const void*): Assertion `writing_rank != ALL_RANKS' failed.
```

This is compiled with 
```-DCMAKE_CXX_FLAGS="-O3 -march=native" -DVR_USE_HYDRO=ON -DVR_MPI=ON```

and run without MPI. This setup definitely worked in the recent past. Any ideas?

**Comment by rtobar** [comment]
@ymbahe can you point me to the full log file? This is a recent check I introduced while working on #88, but there clearly is some mistake for some some unaccounted for cases.

Note that it should be possible to work around this by building with `-DCMAKE_BUILD_TYPE=Release`.

**Comment by ymbahe** [comment]
Hi @rtobar -- the full log file is at /cosma7/data/dp004/dc-bahe1/BH_REPOS/stdres_base2_velcut0p5/logs/vr.3651220.out (and .../vr.3651220.err for the error file). The log file actually has a warning message at the top:
```
MPI startup(): PMI server not found. Please set I_MPI_PMI_LIBRARY variable if it is not a singleton case.
```
Not sure whether this is related though. I'll try your workaround later; I found an older binary file in the meantime which seems to work too.

**Comment by rtobar** [comment]
@ymbahe please try the new `issue-113` branch, I believe that should fix things for you.

As expected, this seems to have just been a problem in an assertion and not in actual code, and which was triggered only by non-Release builds when compiling against a non-parallel HDF5 library (which is your case, based on the contents of your logfile). So please give the new branch a try, and after confirmation I'll merge to the `master` branch.

**Comment by ymbahe** [comment]
Hi @rtobar, thanks for the fix. Yes, it looks like this works fine, so it can be merged to the master.

**Comment by rtobar** [comment]
Great, I've merged the fix to the `master` branch now.
