### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by davidharvey1986** [ICRAR/VELOCIraptor-STF#126]
**Describe the bug**
I am compiling VR and I receive the error 

error: redefinition of 'class vr::exception'

And it fails to compile

**To Reproduce**
export CC=gcc-12
export CXX=g++-12
cmake ..
make all

**Expected behavior**
To compile

**Log files**
If applicable, add log of bug to help explain your problem.

**Environment (please complete the following information):**
 - OS: MAC M1 Max Ventura 13.1
 - Libraries  GCC-12 G++-12 ( from Brew ), libomp 16.0.1 (brew), GSL 2.7.1 (brew) 
 - Version 1.60

**Additional context**
Apologies if this is the wrong place for this.

**Comment by davidharvey1986** [comment]
[cmake_config.log](https://github.com/ICRAR/VELOCIraptor-STF/files/11283519/cmake_config.log)
[cmake.log](https://github.com/ICRAR/VELOCIraptor-STF/files/11283520/cmake.log)

**Comment by rtobar** [comment]
Thanks @davidharvey1986 for reporting this.

I see two issues:
 * Our `src/exceptions.h` header doesn't have an include guard, I'll add one.
 * Mac's filesystem lookups seem to be case-insensitive, which is causing `src/exceptions.cxx`'s `#include "exceptions.h"` to include `src/exceptions.h` (fine), but also making `NBodylib/src/Math/NBodyMath.h`'s `#include <Exceptions.h>` to include `src/exceptions.h` instead of `NBodylib/src/Math/Exceptions.h` (not fine), which causes the error. I think that's easily fixable, but I'll require confirmation from your side to know if that's the case.

**Comment by rtobar** [comment]
@davidharvey1986 please try compiling the `issue-126` branch, which has an update that fixes both issues above. Beware that you'll need to run `git submodule update` as the `NBodylib` submodule has fixes that need to be brought it too.

**Comment by davidharvey1986** [comment]
Hi @rtobar. Thanks for responding. This indeed was my conclusion and by specifically stating the exact file path had temporarily fixed the problem on myside. This fix has now solved the issue so thank you....however.... 

It now doesn't find the  HOST_NAME_MAX, which on my limited knowledge is not something that is valid on a MAC (and is not defined in the machine headers) by changing thi tos _SC_ HOST_NAME_MAX works, but I don't know if there is a subtle difference.

Thanks
[output.log](https://github.com/ICRAR/VELOCIraptor-STF/files/11370903/output.log)

**Comment by rtobar** [comment]
@davidharvey1986 thanks for reporting that further issue. Using `_SC_HOST_NAME_MAX` is not exactly correct; however the fully correct way of doing this in all platforms is a bit clunky, so I'll just replace with `100` -- it's a small detail that won't kill anyone.

**Comment by rtobar** [comment]
@davidharvey1986 just pushed a further commit to the `issue-126` branch, please let me know if that works.

**Comment by davidharvey1986** [comment]
This has now compiled. Thank you for your help!

**Comment by rtobar** [comment]
Great, I'll merge as soon as I get back to my laptop.

**Comment by rtobar** [comment]
Merged to master now, thanks!
