### ISSUE TITLE
Particle_type_for_reference_frames value not listed in the output

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#127]
The value of the configuration parameter `Particle_type_for_reference_frames` is not listed in the output `xxx.configuration` file.

It should be a one-line fix in `ConfigInfo::ConfigInfo()` to dump `opt.ParticleTypeForRefenceFrame`.

**Comment by rtobar** [comment]
@MatthieuSchaller could you have a look at https://github.com/ICRAR/VELOCIraptor-STF/commit/c032aee143b0daa8aee992eacdfb4ac1d10745bd? I tried locally and it seems to work. I'll merge to `master` after confirmation.

**Comment by MatthieuSchaller** [comment]
Yes, works as expected. Thanks!

**Comment by rtobar** [comment]
Great, merged now,, thanks!
