### ISSUE TITLE
Deprecated POSIX time function used in the utilities

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#29]
The function GetMilliCount() in utilities.cxx makes use of the `ftime()` system (POISX) function which is now deprecated. https://man7.org/linux/man-pages/man3/ftime.3.html

GCC 9.x.y reports this as a warning. The function may in principle be absent on some systems.

**Comment by rtobar** [comment]
Fixed on the `master`, thanks!
