### ISSUE TITLE
Swift+VR on Cosma7 with new modules

### ISSUE THREAD

**Issue by stuartmcalpine** [ICRAR/VELOCIraptor-STF#33]
Trying to compile Swift+VR on Cosma7 using the new modules. This is min example that I'm having trouble getting working.

module load intel_comp/2020-update2 
module load intel_mpi/2020-update2
module load ucx/1.8.1 
module load parmetis/4.0.3-64bit 
module load parallel_hdf5/1.10.6 
module load fftw/3.3.8cosma7 
module load gsl/2.5

Configured VR using:

**cmake -DCMAKE_BUILD_TYPE=Release -DVR_USE_SWIFT_INTERFACE=ON -DCMAKE_CXX_FLAGS="-fPIC" ..**

Configured Swift using:

**./configure --with-velociraptor=/vrdir/**

Gives the error:

ipo: error #11021: unresolved gsl_multifit_nlinear_trs_lmaccel
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_trust
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_default_parameters
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_alloc
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_residual
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_position
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_init
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_driver
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_free
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: remark #11001: performing single-file optimizations
ipo: remark #11006: generating object file /tmp/ipo_icc22Mhex.o
icc: error #10014: problem during multi-file optimization compilation (code 1)
make[2]: *** [swift] Error 1
make[2]: *** Waiting for unfinished jobs....
ipo: error #11021: unresolved gsl_multifit_nlinear_trs_lmaccel
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_trust
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_default_parameters
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_alloc
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_residual
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_position
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_init
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_driver
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: error #11021: unresolved gsl_multifit_nlinear_free
        Referenced in libvelociraptor.a(Fitting.cxx.o)
ipo: remark #11001: performing single-file optimizations
ipo: remark #11006: generating object file /tmp/ipo_icc2P8zjg.o
icc: error #10014: problem during multi-file optimization compilation (code 1)
make[2]: *** [swift_mpi] Error 1
make[2]: Leaving directory `/cosma7/data/dp004/rttw52/swift_runs/runs/Sibelius/swiftsim/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/cosma7/data/dp004/rttw52/swift_runs/runs/Sibelius/swiftsim'
make: *** [all] Error 2

**Comment by stuartmcalpine** [comment]
In case it means anything, there is this warning during cmake for VR

CMake Warning (dev) at CMakeLists.txt:228 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.  Environment variable MPI_ROOT is set to:    /cosma/local/intel/Parallel_Studio_XE_2020/impi/2019.8.254/  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:285 (find_mpi)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by rtobar** [comment]
@stuartmcalpine I don't personally have access to cosma, so I'm working with what you posted.

The problem with the missing gsl options seems to indicate that swift is getting linked against a gsl library different from the one VR was compiled against. I'm not sure if the gsl installations under the gsl/2.5 module will automatically be visible to the swift configure script. Don't you need to configure swift with `--with-gsl=something` (e.g., `--with-gsl=$GSL_ROOT` or similar) for it to pick up the GSL module you loaded? Again, this is just a guess given I cannot access the system.

The MPI_ROOT warning issued by the VR configuration seems like an unrelated matter. I'd recommend to follow that separately, but for the time being I'd ignore it in favour on focusing on the GSL compilation issue.

**Comment by jchelly** [comment]
This was caused by an extra -L/usr/lib64/ flag which had been used when compiling HDF5 on Cosma. This made Swift pick up an older libgsl from /usr/lib64/ even when the full path to the right GSL was specified by --with-gsl=... . I've rebuilt HDF5 without the offending flag and Swift picks up the right libgsl now.

The MPI_ROOT message has started appearing because we also installed a newer cmake on Cosma and it warns that the way it finds MPI has changed. It doesn't seem to be a problem for Swift or Velociraptor, at least on systems I've used. The warning can be prevented with something like
```
if(POLICY CMP0074)
  cmake_policy(SET CMP0074 NEW)
endif()
```
or by requiring cmake >= 3.12 in CMakeLists.txt.

**Comment by rtobar** [comment]
Thanks @jchelly for the clarifications on the underlying issue in Cosma.

The change to a newer cmake indeed introduces the new policy on the usage of `_ROOT` variables to find packages. As you experienced this doesn't affect the VR compilation (because `find_package(MPI)` is most probably looking for `mpicc` which is in the `PATH` anyway), but it won't hurt to indeed set the policy explicitly to `NEW`.
