### ISSUE TITLE
Segmentation fault in AdjustStructureForPeriod when running on the fly in Swift

### ISSUE THREAD

**Issue by jchelly** [ICRAR/VELOCIraptor-STF#34]
This has been observed in several simulations but one quick way to reproduce it is the examples/SmallCosmoVolume/SmallCosmoVolume_DM example in the Swift repository. The problem appears to have been introduced in VR commit b5e1a8c5adc9a7c4e637385a8ff77a5c3b643685.

I'm using the latest ICRAR VR master (a497fe32e16995771b0631c1eff47753e918b7b6) configured with:
```
cmake .. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_C_COMPILER=icc \
    -DCMAKE_CXX_COMPILER=icpc \
    -DVR_USE_SWIFT_INTERFACE=ON \
    -DVR_USE_GAS=OFF
```
and the latest Swift master (5fab1cdb81e869fd3adf198a7e0509f5e87eb093) configured with:
```
../configure \
    --enable-debug \
    --with-velociraptor=`pwd`/../../VELOCIraptor-STF/build/src
```

The parameter files I'm using are from the Swift repository - see examples/SmallCosmoVolume/SmallCosmoVolume_DM/small_cosmo_volume_dm.yml and examples/SmallCosmoVolume/SmallCosmoVolume_DM/vrconfig_3dfof_subhalos_SO_hydro.cfg.

To run it:
```
cd swiftsim/examples/SmallCosmoVolume/SmallCosmoVolume_DM
./getIC.sh
mpirun -np 1 ../../../build/examples/swift_mpi --cosmology --self-gravity --velociraptor --threads=16 small_cosmo_volume_dm.yml
```
It runs for a few minutes and crashes when it gets to a redshift ~3:
```
0: finished FOF search in total time of 3.17214
[login7c:219197:0:219197] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))

/cosma7/data/dp004/jch/Swift/repro_bug/VELOCIraptor-STF/src/search.cxx: [ AdjustStructureForPeriod() ]
      ...
      976     for (i=0;i<nbodies;i++) {
      977         if (pfof[i]==0) continue;
      978         if (irefpos[pfof[i]] != -1) continue;
==>   979         refpos[pfof[i]] = Coordinate(Part[i].GetPosition());
      980         irefpos[pfof[i]] = i;
      981     }
      982 #ifdef USEOPENMP

==== backtrace (tid: 219197) ====
 0 0x000000000071d5c2 AdjustStructureForPeriod()  /cosma7/data/dp004/jch/Swift/repro_bug/VELOCIraptor-STF/src/search.cxx:979
 1 0x0000000000715e4b SearchFullSet()  /cosma7/data/dp004/jch/Swift/repro_bug/VELOCIraptor-STF/src/search.cxx:482
 2 0x000000000058e652 InvokeVelociraptorHydro()  /cosma7/data/dp004/jch/Swift/repro_bug/VELOCIraptor-STF/src/swiftinterface.cxx:615
 3 0x000000000058c837 InvokeVelociraptor()  /cosma7/data/dp004/jch/Swift/repro_bug/VELOCIraptor-STF/src/swiftinterface.cxx:398
 4 0x00000000005686ba velociraptor_invoke..0()  /cosma7/data/dp004/jch/Swift/repro_bug/swiftsim/build/examples/../../src/velociraptor_interface.c:1026
 5 0x00000000005824a0 engine_check_for_dumps()  /cosma7/data/dp004/jch/Swift/repro_bug/swiftsim/build/examples/../../src/engine.c:2974
 6 0x000000000041331a engine_step()  /cosma7/data/dp004/jch/Swift/repro_bug/swiftsim/build/examples/../../src/engine.c:2819
 7 0x000000000041331a engine_step()  /cosma7/data/dp004/jch/Swift/repro_bug/swiftsim/build/examples/../../src/engine.c:2828
 8 0x000000000040f1cd main()  /cosma7/data/dp004/jch/Swift/repro_bug/swiftsim/build/examples/../../examples/main.c:1490
 9 0x0000000000022555 __libc_start_main()  ???:0
10 0x000000000040cda9 _start()  ???:0
=================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 219197 RUNNING AT login7c.pri.cosma7.alces.network
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```
The problem is that on line 979 pfof[i]=4627676946019562717, which is clearly not a valid array index. The index i=262144 at this point. This simulation has 262144 particles. The array pfof has more values than this (I think because particles are duplicated so that threads have whole groups to work on) and it seems to be the extra elements after the first 262144 which have problematic values.

I haven't been able to reproduce this running standalone VR on the same simulation.

**Comment by jchelly** [comment]
Ok, I think my comment above is irrelevant. These functions only get called with >1 MPI rank but I can only make it crash when running on one rank.

**Comment by jchelly** [comment]
This crash only happens if running from Swift on the fly, with MPI enabled, and with one MPI rank. I now think the cause is this chunk of code in search.cxx near line 459:
```
        // Delete exported particles
        for (i = Nlocal-1; i >= 0; i--)
          if (Part[i].GetPotential() ==1.0) Part.pop_back();
          else break;
        Nlocal = Part.size();
```
This is going to go wrong if the size of the vector Part is not initially equal to Nlocal. Part is initialized in main.cxx or swiftinterface.cxx depending on whether we're running on the fly or not. The Swift interface always allocates space for imported particles if we're using MPI, but main.c does not allocate the extra space if NProcs==1. So if we're running from Swift the block of code above leaves Nlocal larger than it should be and we get a crash in AdjustStructureForPeriod.

**Comment by rtobar** [comment]
Thanks @jchelly for the great analysis and the proposed solution!

> Part is initialized in main.cxx or swiftinterface.cxx depending on whether we're running on the fly or not. The Swift interface always allocates space for imported particles if we're using MPI, but main.cxx does not allocate the extra space if NProcs==1. So if we're running from Swift with one MPI rank the block of code above leaves Nlocal larger than it should be and we get a crash in AdjustStructureForPeriod.

This might be better suited to be discussed in the PR, but since I'm here... It wasn't obvious to me how adjusting `Nmemlocal` in `main.cxx` would fix the issue, but then I found these, which I think is what you meant?
https://github.com/ICRAR/VELOCIraptor-STF/blob/a4c0e004eacf05a7bd6c5d5a0a972d04b2be8f9b/src/search.cxx#L381-L384
https://github.com/ICRAR/VELOCIraptor-STF/blob/a4c0e004eacf05a7bd6c5d5a0a972d04b2be8f9b/src/search.cxx#L391

**Comment by jchelly** [comment]
If NProcs>1 then line 391 resizes Part to just the right size and everything is ok. The problem is that with NProcs=1 the Swift interface makes Part too big and it doesn't get resized because line 391 is not executed. My solution is just ensuring that Part is the right size initially so we don't need to resize it. There are a couple of other ways to fix this that should also work:

  * Always do Part.resize(Nlocal) in search.cxx no matter how many MPI ranks are in use. 
  * Rewrite the 'delete exported particles' block so it doesn't assume there are no extra unused elements in Part. I don't know if any later code relies on Part.size()==Nlocal so I don't like that one.

**Comment by rtobar** [comment]
Right, I was slightly confused but almost on track... thanks for that clarification!
