### ISSUE TITLE
Typo in hdf5 compression define

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#45]
The ifdef on this line 

https://github.com/ICRAR/VELOCIraptor-STF/blob/bab76598c65b80446b4bc846ffb0db9442c31254/src/hdfitems.h#L846

seems to be incorrect. It should likely be `USEHDFCOMPRESSION`.

**Comment by rtobar** [comment]
True, that's a clear typo. Apparently in older versions the macro was defined within the file itself (with the typo) instead of being a configuration-time option, so it looks like the code was exercised at some point. The definition was later on moved out and into the cmake infrastructure, where the macro name was correctly spelled. I'll fix the typo and hope for the best!

**Comment by rtobar** [comment]
Merged to `master`, thanks again for pointing it out!

**Comment by MatthieuSchaller** [comment]
Actually, I am still stuck. I can't seem to find the right way of activating that ifdef via cmake. 

I can see `ALLOWCOMPRESSIONHDF5` in CMakeLists.txt but I don't see how that relates to the actual macro. Note that I have no understanding of any of the cmake magic so I am very likely looking at the wrong place.

**Comment by rtobar** [comment]
Yes, this is far from obvious: the cmake options are not named like the macro definitions. On top of that, there are two different options to enable this when using serial or parallel hdf5. Long story short, you want to add `-DVR_ALLOWCOMPRESSIONPARALLELHDF5=ON` to the initial cmake invocation.

The cmake options are `VR_ALLOWCOMPRESSIONHDF5` and `VR_ALLOWCOMPRESSIONPARALLELHDF5`. They default to `ON` and `OFF`, respectively (again, not obvious):

https://github.com/ICRAR/VELOCIraptor-STF/blob/fee3a9f7c472fdd2a3a42aa213ee1f9a8b167d8b/CMakeLists.txt#L47-L49

In the case of `VR_ALLOWCOMPRESSIONPARALLELHDF5` it is only considered for hdf5 >= 1.10 (probably to make sure certain behavior is met). In both cases when the option is `ON` the `USEHDFCOMPRESSION` macro is defined:

https://github.com/ICRAR/VELOCIraptor-STF/blob/fee3a9f7c472fdd2a3a42aa213ee1f9a8b167d8b/CMakeLists.txt#L210-L224

**Comment by MatthieuSchaller** [comment]
Thanks! Works perfectly!
