### ISSUE TITLE
Possible problem with M_200_star

### ISSUE THREAD

**Issue by Moyoxkit** [ICRAR/VELOCIraptor-STF#48]
I am running VR (version 1.60) on low resolution SWIFT runs, this particular box is 100^3Mpc with 180^3 particles (M_dm = 5.45e9, M_gas = 1.02e9). When analysing one of the observables we are interested in, namely baryon/gas fractions of halos, the baryon fraction was a lot higher than expected.

Upon further inspection it appears the values of the values obtained for M_200_crit_star (And possibly also M_200_mean_star, M_500_star etc.) are systematically higher than what would be expected.
To show this I compared the M_200 obtained from VR for the different components with the naive method of summing the mass of all particles of that component found within R_200_crit obtained from VR as can be seen in the figure below
![MvsM](https://user-images.githubusercontent.com/37077325/99642761-231e4700-2a4c-11eb-9513-340128ef8e9a.png)
For DM the results have some difference but are relatively close to the black line (these are also a lot more likely to be sufficiently sampled) For stars, and to a much lesser extent also the gas, the values obtained from the sum are systematically lower. For gas the difference might just be the systematics of my naive method but for stars the difference is very large.

Here are some examples of halos with very high baryons fractions and large differences between the sum of stellar mass in R_200_crit and M_200_crit_star
![High_SM_halo_1](https://user-images.githubusercontent.com/37077325/99644060-c15edc80-2a4d-11eb-82f2-a54adb7292fe.png)
log(M_200) [Msun] of this halo:  12.182202934684451
log(M_200_gas) [Msun] of this halo:  11.629046093260513
log(M_200_stars) [Msun] of this halo:  11.64550349357618
r_200 [kpc] of this halo:  237.24077771516048
Dark matter mass (Sum) [log10 Msun] =  12.249682
Gas mass (Sum) [log10 Msun] =  11.431889
Stellar mass (Sum) [log10 Msun] =  11.05762
![High_SM_halo_2](https://user-images.githubusercontent.com/37077325/99644383-27e3fa80-2a4e-11eb-847a-c3bf3dace4d1.png)
log(M_200) [Msun] of this halo:  11.282095177295409
log(M_200_gas) [Msun] of this halo:  10.755906558809153
log(M_200_stars) [Msun] of this halo:  10.783129379073438
r_200 [kpc] of this halo:  118.89221547906023
Dark matter mass (Sum) [log10 Msun] =  11.440651
Gas mass (Sum) [log10 Msun] =  10.576609
Stellar mass (Sum) [log10 Msun] =  9.912582

If you need more information please let me know.

**Comment by MatthieuSchaller** [comment]
Thanks Roi. Can you clarify what the hosthaloID of all of these are? 

Also, if this box is on cosma, can you point people to it?

**Comment by Moyoxkit** [comment]
In the first plot none of the M_200_gas and M_200_star have a positive hosthaloID, All of the M_200 and M_200 dm mass points that are very far above the 1-1 relation (the cloud above it) have positive hosthaloID.

Currently the box in not on cosma but I could move it there.

**Comment by MatthieuSchaller** [comment]
Could you try again with `VR_OPENMP` not set in `cmake`?

**Comment by MatthieuSchaller** [comment]
Roi, is that now fixed? Or are you still seeing issues? 
Also, what happens if you set the core significance threshold to 2?

**Comment by Moyoxkit** [comment]
This was fixed when the OpenMPI issue was fixed a while back, so the issue can be closed

**Comment by rtobar** [comment]
Thanks for following this up @MatthieuSchaller and @Moyoxkit, I'll close this now.
