### ISSUE TITLE
Haloes with Mstar (100 kpc apertures) > M200crit

### ISSUE THREAD

**Issue by EvgeniiChaikin** [ICRAR/VELOCIraptor-STF#51]
<h2> 1. The problem </h2>

Hi all,

In a few of my cosmological runs at `z=0`, VELOCIraptor produces objects with `M_star (100 kpc) / M200crit > 1`. Interestingly, these larger-than-unity ratios seem to only occur if the stellar mass aperture is set to `100 kpc`. For `30-kpc `apertures, I am finding no objects with `M_star (30 kpc) / M200crit > 1`

The problem can be best illustrated using stellar mass vs. halo mass plots. Below are two such plots, for the same run at `z=0`. The top one has `30 kpc` apertures, while the bottom one is with `100 kpc` apertures. I emphasise that in the bottom plot, there are objects **above** the one-to-one line. 

**Fig 1. Stellar mass vs halo mass. The stellar mass is computed in 30-kpc apertures**

![stellar_mass_halo_mass_M200_all_30](https://user-images.githubusercontent.com/20153933/100374061-049beb00-300c-11eb-89ce-39a72833148e.png)
**Fig 2. Same as Fig. 1 but for 100-kpc apertures** 
![stellar_mass_halo_mass_M200_all_100](https://user-images.githubusercontent.com/20153933/100374066-05348180-300c-11eb-9023-ab9e4a3161a5.png)

Below I am displaying one of the objects with `M_star (100 kpc) / M200crit > 1` from the plot above. Interestinlgy, this object has `R200crit = 2.4 kpc ` which is much smaller than `R_aperture = 100 kpc `. Can the latter explain `M_star (100 kpc) / M200crit >> 1`?

**Fig 3. Dark-matter projected density of one of the object with M_star (100 kpc) / M200crit > 1 from Fig. 2**

![4_dm_faceon](https://user-images.githubusercontent.com/20153933/100373780-99eaaf80-300b-11eb-8867-d07002683ea0.png)
**Fig 4. Same as Fig. 3 but the colour traces stellar projected density**

![4_star_faceon](https://user-images.githubusercontent.com/20153933/100373782-9a834600-300b-11eb-8365-958e27f2617a.png)

The fact that there are SMHM ratios **> 1** indicates that there could be a bug in the code. If this is expected behaviour, it would still be great to know what causes these unrealistically high ratios, and also how exactly the 100-kpc-aperture stellar mass is computed in the case that an object has `R200crit << 100 kpc`.

Note that the dark-matter particle mass in my runs is `1.2 \times 10^6 M_\odot`.

<h2> 2. I am using </h2>

- VR from ICRAR repository
- Master branch
- Version
```
commit 7e4683963354bcf2b2730d5f8576ac931f7da43d
Author: Rodrigo Tobar <rtobar@icrar.org>
Date:   Sun Oct 25 20:49:02 2020 +0800
```

<h2> 3. Reproduce this behaviour </h2>

All my data, which I used to make the plots above, can be found on cosma
- Path to the SWIFT snapshot that I fed on VR 
`/snap7/scratch/dp004/dc-chai1/my_cosmological_box/AGN5_L006188_00_CHIMES_NoESO_M16/colibre_2729.hdf5`
- Path to VR output 
`/snap7/scratch/dp004/dcchai1/my_cosmological_box/AGN5_L006188_00_CHIMES_NoESO_M16/halo_2729.*`
- Path to VR config 
`/cosma7/data/dp004/dc-chai1/vrconfig_m16.cfg` 

@MatthieuSchaller

**Comment by rtobar** [comment]
@EvgeniiChaikin is this still an issue? I have to admit I don't know much about the physics here, but recently we've fixed a number of problems across the board, and I was wondering if this might have been fixed "by accident" by any of them.

**Comment by MatthieuSchaller** [comment]
@EvgeniiChaikin any updates on this? Is it still an issue?

**Comment by rtobar** [comment]
@EvgeniiChaikin great! I'll then close this old issue, if the problem is seen again let's just open a new, fresh one.
