### ISSUE TITLE
Crash when reading in temperatures in the branch `hot_gas_properties`

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#52]
There seems to be a mismatch between the population of the array hdf_parts->names and its usage. 

On line 1588 of hdfio.cxx, the code attempts to access `hdf_parts[k]->names[HDFGASTEMP]`. 
`HDFGASTEMP` is defined to be 99 on line 53 of `hdfitems.h`. However, the `names` array is only 39 long and the field we actaully want to access is in position 8. 
Setting `HDFGASTEMP` to 8 solves the immediate problem. However, that seems a bit suspicious as it means the array was not constructed using the named fields of `hdfitems.h` and could hence lead to other problems of the same kind down the line.

**Comment by edoaltamura** [comment]
Thanks @MatthieuSchaller for reporting! I can also run successfully by changing `HDFGASTEMP` and get the mismatched behaviour in the dataset names in new `hot_gas_properties` outputs.

**Comment by rtobar** [comment]
Sorry, I closed this by mistake. Since I'm here: @edoaltamura @JBorrow from the conversation in Slack it seems like Claudia fixed this in the `hot_gas_properties` branch, is that correct? If so we can actually close this; otherwise we can keep it opened.

**Comment by rtobar** [comment]
`2a884ff` seems to be the fix for this issue; I'm therefore closing it, feel free to open a new one if there are any further problems.
