### ISSUE TITLE
One more typo in macro

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#55]
This define has the same typo as was fixed in a previous issue. Maybe worth fixing here for consistency. 

https://github.com/ICRAR/VELOCIraptor-STF/blob/cb4336de8421b7bada3e158c44755c41e9fab78b/src/hdfitems.h#L103

Also, not sure what that whole block is supposed to achieve in general.

**Comment by rtobar** [comment]
Thanks @MatthieuSchaller, this looks like and old mechanism to define/undefine the macro before it was exposed as a cmake option, I'll simply remove those lines.

**Comment by rtobar** [comment]
Fixed on the `master` now.
