### ISSUE TITLE
OpenMP version of SO quantities

### ISSUE THREAD

**Issue by rtobar** [ICRAR/VELOCIraptor-STF#62]
As mentioned in https://github.com/ICRAR/VELOCIraptor-STF/pull/57#issuecomment-776268884 there are a number of datasets that are widely different between runs of VR (standalone, but probably also with SWIFT) that are OpenMP-enabled and OpenMP-disabled.

A full list of the datasets that are different can be derived by comparing the two diffeernt output files mentioned in the comment linked above. I did the following:

```bash
vr_compare_datasets() {
        file1="$1"
        file2="$2"
        dataset="$3"
        lines=15
        diff -Naur <(h5dump -d $dataset "$file1" | head --lines $lines) <(h5dump -d $dataset "$file2" | head --lines $lines)
}

for dataset in `h5dump -n /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/halos_omp_0036.properties.0 | grep SO_ | awk '{print $2}'`; do
    vr_compare_datasets /cosma7/data/dp004/jlvc76/BAHAMAS/Roi_run/halos_{omp_,}0036.properties.0 $dataset
done > so_quantities.diff
```

The [resulting file](https://github.com/ICRAR/VELOCIraptor-STF/files/5986297/so_quantities.diff.txt) shows the differences for all `SO_*` datasets between the two files. The following is a summary of the situation:

Equal
=====

 * /SO_Mass_highT_0.100000_times_500.000000_rhocrit
 * /SO_Mass_highT_0.250000_times_500.000000_rhocrit
 * /SO_Mass_highT_0.500000_times_500.000000_rhocrit
 * /SO_Mass_highT_0.750000_times_500.000000_rhocrit
 * /SO_Mass_highT_1.000000_times_500.000000_rhocrit

Almost equal
============

Only a few values are slightly different, the rest are the same

 * /SO_Mass_1000_rhocrit
 * /SO_Mass_100_rhocrit
 * /SO_Mass_200_rhocrit
 * /SO_Mass_2500_rhocrit
 * /SO_Mass_500_rhocrit
 * /SO_R_1000_rhocrit
 * /SO_R_100_rhocrit
 * /SO_R_200_rhocrit
 * /SO_R_2500_rhocrit
 * /SO_R_500_rhocrit

Minor differences
=================

Most values are different, but only after 2 or 3 decimal places.

 * /SO_Lx_1000_rhocrit
 * /SO_Lx_100_rhocrit
 * /SO_Lx_200_rhocrit
 * /SO_Lx_2500_rhocrit
 * /SO_Lx_500_rhocrit
 * /SO_Lx_gas_1000_rhocrit
 * /SO_Lx_gas_100_rhocrit
 * /SO_Lx_gas_200_rhocrit
 * /SO_Lx_gas_2500_rhocrit
 * /SO_Lx_gas_500_rhocrit
 * /SO_Lx_star_1000_rhocrit
 * /SO_Lx_star_100_rhocrit
 * /SO_Lx_star_200_rhocrit
 * /SO_Lx_star_2500_rhocrit
 * /SO_Lx_star_500_rhocrit

Also all equivalent `Ly` and `Lz` datasets.

Huge differences
================

Most values are different, even already at the most significant decimal place. *Some* values are the same though.

 * /SO_Mass_gas_1000_rhocrit
 * /SO_Mass_gas_100_rhocrit
 * /SO_Mass_gas_200_rhocrit
 * /SO_Mass_gas_2500_rhocrit
 * /SO_Mass_gas_500_rhocrit
 * /SO_Mass_gas_highT_0.100000_times_500.000000_rhocrit
 * /SO_Mass_gas_highT_0.250000_times_500.000000_rhocrit
 * /SO_Mass_gas_highT_0.500000_times_500.000000_rhocrit
 * /SO_Mass_gas_highT_0.750000_times_500.000000_rhocrit
 * /SO_Mass_gas_highT_1.000000_times_500.000000_rhocrit
 * /SO_Mass_star_1000_rhocrit
 * /SO_Mass_star_100_rhocrit
 * /SO_Mass_star_200_rhocrit
 * /SO_Mass_star_2500_rhocrit
 * /SO_Mass_star_500_rhocrit
 * /SO_T_gas_highT_0.100000_times_500.000000_rhocrit
 * /SO_T_gas_highT_0.500000_times_500.000000_rhocrit
 * /SO_T_gas_highT_0.750000_times_500.000000_rhocrit
 * /SO_T_gas_highT_1.000000_times_500.000000_rhocrit
 * /SO_Zmet_gas_highT_0.100000_times_500.000000_rhocrit
 * /SO_Zmet_gas_highT_0.250000_times_500.000000_rhocrit
 * /SO_Zmet_gas_highT_0.500000_times_500.000000_rhocrit
 * /SO_Zmet_gas_highT_0.750000_times_500.000000_rhocrit
 * /SO_Zmet_gas_highT_1.000000_times_500.000000_rhocrit

**Comment by rtobar** [comment]
As a workaround, one obviously can compile the code without OpenMP support.

**Comment by MatthieuSchaller** [comment]
Just to add to the first line in the description: the problem is indeed the same when running inlined.

**Comment by rtobar** [comment]
This was a bit hard to find, but the problem was a race condition on a shared variable used by different OpenMP threads concurrently. Once the issue was found the fix was simple: just declare the variable within each thread.

After applying the fix I ran VR with 4 and 1 thread and compared the outputs using the utility shown in the issue description. No differences were found this time for any of the SO quantities, and therefore the patch seems to work correctly.

I've opened #69 just to double-check I didn't break any of the builds. @MatthieuSchaller I feel confident enough that I will merge this immediately to the `master` branch after the PR is green, but if you could double-check this on your end later on it would be great.

**Comment by rtobar** [comment]
Code merged to `master`.
