### ISSUE TITLE
Unexpected behaviour when VR is applied to cosmological zooms with baryons

### ISSUE THREAD

**Issue by EvgeniiChaikin** [ICRAR/VELOCIraptor-STF#78]
Hi, I recently started working with cosmological zooms of Milky Way-mass haloes and I wanted to apply VELOCIraptor to the data in the same way as I do it for full cosmological boxes. 

When I run VELOCIraptor on zooms to obtain the catalogues, I always find that VR struggles to correctly compute the properties of the central halo and of one of the subhaloes.

What I keep finding instead is that in all  the zoom simulations,

- **Problem A.** an object with the _largest halo mass_ in the simulation, which is for some reason not classified as central, has _too low stellar mass_ and too large r200.
- **Problem B.** an object with a _very small halo mass_, which should not but is classified as central, has _far too large stellar mass_. This object also has a negative r200. **[UPD: this problem is now gone]**

Below is a simple python script that shows what is going on in the VR catalogue in one of the zoom simulations. The object with problem A (problem B) is the last one in the last (first) row of the output. 

```
In [1]: import numpy as np

In [2]: import velociraptor as vr

In [3]: data = vr.load("halo_halo_10_0037.properties") # Load VR catalogue

In [4]: halo_mass = data.masses.mass_200crit  # Fetch halo masses

In [5]: stellar_mass = data.apertures.mass_star_30_kpc # Fetch stellar masses

In [6]: r200 = data.radii.r_200crit # Get r200

In [7]: sort_idx = np.argsort(halo_mass) # Sort according to halo mass

In [8]: stellar_mass.to("Msun")[sort_idx] # Show stellar masses
Out[8]: 
unyt_array([0.00000000e+00, 0.00000000e+00, 5.70441663e+09,  
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
            2.72257719e+06, 0.00000000e+00, 2.57739048e+05,
            1.74264642e+06, 2.02618167e+08, 5.25602289e+08], 'Msun')  # [The largest halo has too low stellar mass]

In [9]: r200.to("kpc")[sort_idx] # Show r200
Out[9]:
unyt_array([-1.00000000e+00, -1.00000000e+00, -6.91574142e-02,
            -1.94654432e+02,  8.12557225e+01,  2.44313447e+01,
             1.32149940e+01,  6.28237402e+00,  8.00385528e+01,
             2.38922979e+01,  3.74907068e+00,  3.73819116e+01,
             1.03565331e+01,  1.64424960e+01,  1.15966419e+01,
             4.34248021e+01,  2.39968011e+01,  2.79605862e+01,
             3.40829283e+01,  3.33680927e+01, -2.75381537e+01,
             1.10373186e+02, -2.33397677e+01,  5.57266117e+02,
             3.56556864e+02,  3.61359039e+02,  1.77724087e+03,
             1.29139616e+03,  8.10693203e+02, 4.50728670e+03], 'kpc') # [r200 seem to be very large for all (sub)haloes]

In [10]: data.structure_type.structuretype[sort_idx] # Show structure types (to see what is central and what is not)
Out[10]: 
unyt_array([10, 10, 10, 
            10, 20, 20, 
            20, 25, 20, 
            35, 20, 30, 
            20, 30, 30,
            20, 20, 30, 
            30, 30, 10, 
            30, 10, 20, 
            25, 25, 15, 
            15, 15, 20],  dtype=int32, units='dimensionless')  # [the largest halo is not a central]

```

**Visualisation of the problematic (sub)haloes**

The gas surface density and dark matter mass surface density of the object with problem A are

![6_dens_faceon](https://user-images.githubusercontent.com/20153933/119228355-f50ce300-bb12-11eb-9869-58df9288f050.png)
![6_dm_faceon](https://user-images.githubusercontent.com/20153933/119228356-f5a57980-bb12-11eb-9d7c-dadaa0a7cb1b.png)

The gas surface density and dark matter mass surface density of the object with problem B are

![0_dens_faceon](https://user-images.githubusercontent.com/20153933/119228371-05bd5900-bb13-11eb-9094-3430505875fc.png)
![0_dm_faceon](https://user-images.githubusercontent.com/20153933/119228372-05bd5900-bb13-11eb-91ca-1c36fc9fb3da.png)

**To reproduce the bug**

- Path to the snapshot `/cosma7/data/dp004/dc-chai1/zooms/batch1_12_05_21/halo_10/snapshot_halo_10_0037.hdf5`
- Path to VR config `/cosma7/data/dp004/dc-chai1/vrconfig_3dfof_subhalos_SO_hydro_final2_zoom.cfg`
- Path to VR` /cosma7/data/dp004/dc-chai1/VR_ICRAR_27_March/VELOCIraptor-STF/build/stf`
- VR version: master branch (`64de17bff6925f47f3ebe8f8195108801d661d95`, March 24, 2021)

**VR was compiled as:**

`cmake -DVR_USE_GAS=ON -DVR_USE_STAR=ON -DVR_USE_BH=ON -DVR_MPI=NO`

I tried compiling with  `-DVR_ZOOM_SIM` but that didn't help.

I think that the problems occur because I am using a VR config that was originally designed for full cosmological boxes (not zooms). The solution will therefore most likely involve tweaking a few parameters in the VR config.

@MatthieuSchaller

**Comment by MatthieuSchaller** [comment]
Thanks for the full report Evgenii. 

Indeed, this setup differs in two was from our normal runs:
 - zoom
 - different set of units.
 
 However, the problem is somewhat reminiscent of the centering issues we have had in the past. This was at the time fixed by demanding that the haloes are always centred on a DM particle and not just any kind. 
 Could something like that be at play here once more?

**Comment by MatthieuSchaller** [comment]
Also, do we believe A & B should be a single object with the correct total stellar, gas and DM mass?

**Comment by EvgeniiChaikin** [comment]
> Also, do we believe A & B should be a single object with the correct total stellar, gas and DM mass?

@MatthieuSchaller the two figures below should clarify what is going on

![xy_vis](https://user-images.githubusercontent.com/20153933/119274852-4a7be980-bc12-11eb-881f-3d933bc1ad37.png)
![xz_vis](https://user-images.githubusercontent.com/20153933/119274855-4b148000-bc12-11eb-8310-f2067409ba62.png)

**Comment by EvgeniiChaikin** [comment]
**UPDATE!**

I figured what was causing part of the problem. When I was specifying the units for the Hubble parameter in the config file, I wrongly assumed that its units follow the standard cosmological convention, which is km/s/Mpc. However, since the value of H0 actually needs to be provided in internal units and my internal units in the simulation are [M,L,V] =  [1e10Msun, km/s, kpc], what I should have used instead is km/s/kpc.

Now the **problem B** is gone. But the **problem A** remains. That is, the object with the largest M200 still has too low stellar mass, too large r200, and is not identified as central. However, its origin can now be interpreted differently.

The object's dark matter surface density distribution is the same as what I provided in the description.

![6_dm_faceon](https://user-images.githubusercontent.com/20153933/119277996-f4fc0880-bc22-11eb-908b-6183e7e52a87.png)

However, now the second-largest object is the central, which seems to have the correct stellar mass and r200.

![0_dm_faceon](https://user-images.githubusercontent.com/20153933/119278196-faa61e00-bc23-11eb-9051-8bd9416a4828.png)

Its position coincides with that of the largest object.

![xy_vis](https://user-images.githubusercontent.com/20153933/119278225-2e814380-bc24-11eb-9caa-7d3cb588c870.png)

I am now guessing that if we simply ignore the first object, everything will become correct. It appears that VR is thinking of the whole zoom-in region as if it was an additional halo, which is why we have a halo with an incredibly large r200 (problem A).

**Comment by MatthieuSchaller** [comment]
Would the remaining issue be fixed by compiling in zoom mode and switching on the parttype 2 particles in the config?

**Comment by EvgeniiChaikin** [comment]
Changing `Input_includes_extradm_particle=0` to `Input_includes_extradm_particle=1` does not help (does not help = problem A is still there)

Changing `Halo_core_phase_significance=5.0` to `Halo_core_phase_significance=2.0` does not help either (althogh it has effect on the masses of substructued.

I also tried running with `-DVR_ZOOM_SIM` (and with `Input_includes_extradm_particle=1`) but in this case VR seg-faulted.

**Comment by EvgeniiChaikin** [comment]
The problem with too large r200 and assigning large halo masses to haloes which, based on the density field, should not have them seems to be not unique to the example I showed above. Here is another one

![xy_vis](https://user-images.githubusercontent.com/20153933/119524958-63a1a900-bd7e-11eb-83f2-f22b3c3c8f8b.png)

**Comment by EvgeniiChaikin** [comment]
Probably a more interesting and illustrative example can be found in `/cosma7/data/dp004/dc-chai1/zooms/batch1_12_05_21/halo_5` (snapshot `snapshot_halo_5_0037.hdf5`)

Below are images of two of the three largest (by M200_crit) DM haloes. Clearly, in both cases, r200 and M200 are too large.

![0_dm_faceon](https://user-images.githubusercontent.com/20153933/119528655-aca72c80-bd81-11eb-9f35-35ba057e6ebb.png)
![5_dm_faceon](https://user-images.githubusercontent.com/20153933/119528657-ad3fc300-bd81-11eb-8923-a04db6aeb48e.png)

**Comment by MatthieuSchaller** [comment]
@EvgeniiChaikin have you tried a more recent master? Also, when changing units, did you also update G, not just H0?

@edoaltamura could you share the code version, modules, VR config and full parameter file you use for the XL cluster zooms?

**Comment by edoaltamura** [comment]
Hi @EvgeniiChaikin and @MatthieuSchaller, see below the setup I use.

Modules:
```
module purge
module load cmake/3.18.1
module load intel_comp/2020-update2
module load intel_mpi/2020-update2
module load ucx/1.8.1
module load parmetis/4.0.3-64bit
module load parallel_hdf5/1.10.6
module load fftw/3.3.8cosma7
module load gsl/2.5
```
Compile with:
```
cmake . \
    -DVR_USE_HYDRO=ON \
    -DVR_USE_SWIFT_INTERFACE=OFF \
    -DCMAKE_CXX_FLAGS="-fPIC" \
    -DCMAKE_BUILD_TYPE=Release \
    -DVR_ZOOM_SIM=ON \
    -DVR_MPI=OFF
  make -j
```
Note, I do recommend compiling with MPI due to some negative density issues and better performance, just haven't done that myself.
Then run with: `-C /cosma/home/dp004/dc-alta2/snap7/xl-zooms/hydro/vrconfig_3dfofbound_subhalos_SO_hydro.cfg` with the same modules imported.
I see you have compiled with `-DVR_ZOOM_SIM=ON`, but there might be also some zoom-specific parameters to tweak in the `.cfg`. I will take a look at your config file, but do feel free to try with/copy mine if it helps!

**Comment by EvgeniiChaikin** [comment]
> @EvgeniiChaikin have you tried a more recent master? Also, when changing units, did you also update G, not just H0?
> 
> @edoaltamura could you share the code version, modules, VR config and full parameter file you use for the XL cluster zooms?

Yes, I changed the gravity constant too. (otherwise there would be no decected haloes at all)

I haven't used the most recent master yet; should definitely give it a try!

**Comment by EvgeniiChaikin** [comment]
> Hi @EvgeniiChaikin and @MatthieuSchaller, see below the setup I use.
> 
> Modules:
> 
> ```
> module purge
> module load cmake/3.18.1
> module load intel_comp/2020-update2
> module load intel_mpi/2020-update2
> module load ucx/1.8.1
> module load parmetis/4.0.3-64bit
> module load parallel_hdf5/1.10.6
> module load fftw/3.3.8cosma7
> module load gsl/2.5
> ```
> 
> Compile with:
> 
> ```
> cmake . \
>     -DVR_USE_HYDRO=ON \
>     -DVR_USE_SWIFT_INTERFACE=OFF \
>     -DCMAKE_CXX_FLAGS="-fPIC" \
>     -DCMAKE_BUILD_TYPE=Release \
>     -DVR_ZOOM_SIM=ON \
>     -DVR_MPI=OFF
>   make -j
> ```
> 
> Note, I do recommend compiling with MPI due to some negative density issues and better performance, just haven't done that myself.
> Then run with: `-C /cosma/home/dp004/dc-alta2/snap7/xl-zooms/hydro/vrconfig_3dfofbound_subhalos_SO_hydro.cfg` with the same modules imported.
> I see you have compiled with `-DVR_ZOOM_SIM=ON`, but there might be also some zoom-specific parameters to tweak in the `.cfg`. I will take a look at your config file, but do feel free to try with/copy mine if it helps!

Thanks Edo! I will check your version tomorrow. Hopefully, VR won't be complaing anymore!

**Comment by EvgeniiChaikin** [comment]
I have just tried the following. Explaining everying step by step.

1. Switch to most recent master 

 `bfd106824c003b831c41779f76d09f8981c3926a` (May 26, 2021)

2. Ensure all modules are loaded 
```
[dc-chai1@login7c build]$ module list
Currently Loaded Modulefiles:
 1) cmake/3.18.1   3) intel_comp/2020-update2   5) parmetis/4.0.3-64bit   7) fftw/3.3.8cosma7  
 2) ucx/1.8.1      4) intel_mpi/2020-update2    6) parallel_hdf5/1.10.6   8) gsl/2.5
```
3. Compile as recommended by @edoaltamura 

`cmake .. -DVR_USE_HYDRO=ON -DVR_USE_SWIFT_INTERFACE=OFF -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_BUILD_TYPE=Release -DVR_ZOOM_SIM=ON -DVR_MPI=OFF`

4. Build

`make -j`

5. Copy @edoaltamura config to a new file (`vrconfig_edo.cfg`) and adjust the units of lengths, G, and H0 because my zooms have kpc instead of Mpc

```
[dc-chai1@login7c dc-chai1]$ diff vrconfig_edo.cfg /cosma/home/dp004/dc-alta2/snap7/xl-zooms/hydro/vrconfig_3dfofbound_subhalos_SO_hydro.cfg
25,27c25,27
< #assumes input is in 1e10 msun, kpc and km/s and output units are the same
< Gravity=43000.0211349 #for 1e10 Msun, km/s and kpc
< Hubble_unit=0.100 # assuming units are km/s and kpc, then value of Hubble in km/s/kpc
---
> #assumes input is in 1e10 msun, Mpc and km/s and output units are the same
> Gravity=43.0211349 #for 1e10 Msun, km/s and Mpc
> Hubble_unit=100.0 # assuming units are km/s and Mpc, then value of Hubble in km/s/Mpc
30c30
< Length_unit_to_kpc=1.0
---
> Length_unit_to_kpc=1000.0
156a157
> 
[dc-chai1@login7c dc-chai1]$ 
```
6. Try running VR on one of zooms

```
export OMP_NUM_THREADS=1

COSMA_PATH="/cosma7/data/dp004/dc-chai1/"

${COSMA_PATH}/VR_ICRAR_27_March/VELOCIraptor-STF_zoom/build/stf \
-C ${COSMA_PATH}/vrconfig_edo.cfg \
-i ${COSMA_PATH}/zooms/batch1_12_05_21/halo_5/snapshot_halo_5_0037 \
-o ${COSMA_PATH}/zooms/batch1_12_05_21/halo_5/halo_halo_5_0037 -I 2
```

7. Result. **seg-fault**

```
[  26.253] [ info] main.cxx:439 Baryon search with 1 threads finished in 4.647 [s]
[  26.253] [debug] search.cxx:3983 Getting Hierarchy 764
[  26.253] [debug] search.cxx:4016 Done
[  26.258] [ info] substructureproperties.cxx:5025 Sort particles and compute properties of 764 objects
[  26.258] [debug] substructureproperties.cxx:5037 Calculate properties using minimum potential particle as reference
[  26.258] [debug] substructureproperties.cxx:5040 Sort particles by binding energy
[  27.292] [debug] substructureproperties.cxx:5065 Memory report at substructureproperties.cxx:5065@long long **SortAccordingtoBindingEnergy(Options &, long long, NBody::Particle *, long long, long long *&, long long *, PropData *, long long): Average: 1.330 [GiB] Data: 1.261 [GiB] Dirty: 0 [B] Library: 0 [B] Peak: 1.459 [GiB] Resident: 1.260 [GiB] Shared: 8.379 [MiB] Size: 1.360 [GiB] Text: 3.289 [MiB] 
[  27.292] [debug] substructureproperties.cxx:42 Getting CM
[  27.308] [debug] substructureproperties.cxx:320 Done getting CM in 15 [ms]
[  27.308] [debug] substructureproperties.cxx:4599 Getting energy
[  44.721] [debug] substructureproperties.cxx:4711 Have calculated potentials in 17.412 [s]
[  44.750] [debug] substructureproperties.cxx:5012 Done getting energy in 17.441 [s]
[  44.750] [debug] substructureproperties.cxx:338 Getting bulk properties
[  46.806] [debug] substructureproperties.cxx:2195 Done getting properties in 2.056 [s]
[  46.807] [debug] substructureproperties.cxx:3215 Done FOF masses in 124 [us]
[  46.972] [debug] substructureproperties.cxx:3232 Get inclusive masses
[  46.972] [debug] substructureproperties.cxx:3233  with masses based on full SO search (slower) for halos only
[  47.012] [trace] substructureproperties.cxx:3313 Building trees for SO search
[  51.105] [trace] substructureproperties.cxx:3332 Max search distance is 1003.220 in period fraction 0.010
Segmentation fault
```

Clearly something is wrong, but I don't see what...

**Comment by rtobar** [comment]
@EvgeniiChaikin the segmentation fault was a problem in the code, not on your setup (but your setup helped surfacing the problem). I've pushed a fix for it on the `issue-78` branch which fixes the problem (I double-checked running exactly like you specified in your commands above). I've created a PR to double-check that nothing is broken, and after that I'll merge directly to the `master`.

**Comment by rtobar** [comment]
The fix is now on the `master` branch after the PR successfully passed all the checks.

**Comment by EvgeniiChaikin** [comment]
Thank you very much @rtobar!

My seg fault is gone too! And running with `-DVR_ZOOM_SIM=ON` produces all haloes with plausible masses and sizes!

I am therefore closing this issue because everyting has been fixed.

Thank you all again!

**Comment by MatthieuSchaller** [comment]
Fantastic. Thanks all.
