### ISSUE TITLE
Uninitialised gas SFR threshold

### ISSUE THREAD

**Issue by rtobar** [ICRAR/VELOCIraptor-STF#79]
While reading the code I found that `Option.gas_sft_threshold` is never initialised: it doesn't have a default value (so it cannot be assumed it takes a fixed value at startup), and there's no place in the code that writes into it (either from the command line, configuration file, or input data files). On the other hand the value is used in a few places in the code, particularly in few of the functions in `substructureproperties.cxx`.

```
$> grep -RIn gas_sfr_threshold src/
src/substructureproperties.cxx:616:                if (SFR>opt.gas_sfr_threshold) pdata[i].M_gas_sf+=mval;
src/substructureproperties.cxx:641:                if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:693:                if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:871:                    if (SFR>opt.gas_sfr_threshold){
src/substructureproperties.cxx:1473:                if (SFR>opt.gas_sfr_threshold) pdata[i].M_gas_sf+=mval;
src/substructureproperties.cxx:1546:                if (SFR > opt.gas_sfr_threshold) {
src/substructureproperties.cxx:1754:                    if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:1809:            if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:5637:            if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:5841:            if (SFR>opt.gas_sfr_threshold) EncMassGasSF+=mass;
src/substructureproperties.cxx:5891:            if (SFR>opt.gas_sfr_threshold) oldrc_gas_sf=rc;
src/substructureproperties.cxx:5993:                if (SFR>opt.gas_sfr_threshold) {
src/substructureproperties.cxx:6071:                if (SFR>opt.gas_sfr_threshold) EncMassGasSF+=mass;
src/substructureproperties.cxx:6116:                if (SFR>opt.gas_sfr_threshold) oldrc_gas_sf=rc;
src/substructureproperties.cxx:6202:        if (Pval->GetSFR()>opt.gas_sfr_threshold)
src/substructureproperties.cxx:6238:        if (sfrval>opt.gas_sfr_threshold)
src/substructureproperties.cxx:6274:        if (Pval->GetSFR()>opt.gas_sfr_threshold)
src/substructureproperties.cxx:6311:        if (sfrval>opt.gas_sfr_threshold)
src/allvars.h:775:    Double_t gas_sfr_threshold;
```

Given the variable is uninitialised, this potentially means some results (basically whatever happens within those `if`s) cannot be guaranteed to be consistent across different compilations/settings/platforms/etc.

The fix should be easy: firstly, make sure the variable has a default value, and secondly, we'll probably need a way to assign arbitrary values for this threshold.

@MatthieuSchaller, I have two questions about this:
 * Is this something that might explain some of the issues found lately (#75, #78)?
 * I assume `0` is a good default value, so I'll go with that. For setting arbitrary values: do you reckon they are supposed to be given via the configuration file (via a new setting), or should they somehow be computed from the input data?

**Comment by MatthieuSchaller** [comment]
Interesting. Might be related to  / leading to #75. 

Now, unfortunately, I don't know what that variable ought to be doing...  
My guess is that it is used to select gas with a star formation rate above a given user-defined threshold. Not sure why one would want to do this for a non-zero threshold. I suppose the only natural value is 0 to select between star-forming and non-star-forming gas. 

Definitely needs to be initialised. Whether it needs to be a parameter I don't know. For EAGLE-related applications that will always be zero anyway.

**Comment by rtobar** [comment]
OK, I'll add a default value of `0` for now. @pelahi, when you have a time: do you have any insights as to the purpose of this setting, and whether this should be controlled via the configuration file?

**Comment by rtobar** [comment]
The change is now on the `master` branch. I'll wait for Pascal's guidance to decide whether we need a new setting or not.

**Comment by pelahi** [comment]
Hi @rtobar @MatthieuSchaller it is the variable that is used to split star forming gas from non-star forming gas so 0 is a good default value. I've just pushed a branch with a fix (default is 0 and has configuration option). Did you want to try
https://github.com/pelahi/VELOCIraptor-STF/tree/bugfix/gas_sfr
I can also create a pull request if desired.

**Comment by rtobar** [comment]
Thanks @pelahi for the very prompt reply! I'll cherry-pick the main bit from https://github.com/pelahi/VELOCIraptor-STF/commit/875a60d82574be893657e4656d0f401dbacbb702 to allow users to provide the setting.

**Comment by rtobar** [comment]
The option is now defaulted to `0` and a new `Gas_star_forming_rate_threshold` setting in the configuration file allows users to specify a different value if required. Thanks again @MatthieuSchaller and @pelahi for your help!

**Comment by MatthieuSchaller** [comment]
Thanks! Just to be extra clear, do we now need to update our config files?

**Comment by rtobar** [comment]
@MatthieuSchaller no, it shouldn't be necessary as the default value of `0` should kick in.
